# Generated by Django 4.0.2 on 2022-09-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginform',
            new_name='login',
        ),
    ]
